# Generated by Django 5.2.13 on 2026-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_alter_workspaceinvitation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.TextField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("nl", "Dutch"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("it", "Italian"),
                    ("pl", "Polish"),
                    ("ko", "Korean"),
                    ("uk", "Ukrainian"),
                    ("pt-br", "Portuguese (Brazil)"),
                ],
                default="en",
                help_text=(
                    "An ISO 639 language code (with optional variant) selected "
                    "by the user. Ex: en-GB."
                ),
                max_length=10,
            ),
        ),
    ]
